# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: f608e3c3c4fc1762bf59d77f2b5cd2921ac81061fc230ce3a5d1a81223023c1b339f8d3255c39291e78deca7d04f70647dcc1e50ad9798431b48d975eb43244a

test:
  secret_key_base: db0eed71ab6abc3f88860a1691e13dc4c0b146ca0bf0fb97fd5da40e7626f3997e55d5eb70112ba4320e9745c942fb396d1d75d556aa12781e678c462cfbee5c

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
